allowBuilds:
  simple-git-hooks: false

dedupePeers: true
dedupePeerDependents: true

enableGlobalVirtualStore: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@changesets/*"

overrides:
  lightningcss: "-"
  postcss: "-"
  rolldown: 1.2.4
  vite: "^8"

savePrefix: ""

trustPolicy: no-downgrade
