allowBuilds:
  simple-git-hooks: false

dedupePeers: true
dedupePeerDependents: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@changesets/*"
  - tsdown@0.22.8

overrides:
  lightningcss: "-"
  postcss: "-"

savePrefix: ""

trustPolicy: no-downgrade
