name: changesets-status

on:
  # zizmor: ignore[dangerous-triggers]
  pull_request_target:

permissions: {} # require explicitly stating all permissions in each job

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  status:
    runs-on: ubuntu-slim
    permissions:
      contents: read # to check out files in the repo
    outputs:
      comment-body: ${{ steps.status.outputs.comment-body }}
    steps:
      - name: Check out repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Generate status
        id: status
        uses: changesets/action/pr-status@c47fa68bd43bb8ae0bae7e558622593deebf5955 # v2.0.0-next.3

  comment:
    needs: status
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write # to create and update comments on PRs
    steps:
      - name: Comment on PR
        uses: changesets/action/pr-comment@c47fa68bd43bb8ae0bae7e558622593deebf5955 # v2.0.0-next.3
        with:
          body: ${{ needs.status.outputs.comment-body }}
