name: codspeed

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - .github/workflows/codspeed.yml
      - src/**
      - pnpm-lock.yaml
      - tsdown.config.ts
      - vitest.config.ts
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  benchmarks:
    runs-on: ubuntu-latest

    permissions:
      contents: read # required for actions/checkout
      id-token: write # required for OIDC authentication with CodSpeed

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: node --run build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@f22792bfac16f3e14eb9fbea76f4a48e9cc22b93 # v4.19.1
        with:
          mode: simulation
          run: node --run bench
